let characters = [
    {
        characterName: "Kirby",
        yamlOptionName: 'kirby_flavor',
        firstColorIndexInYamlOption: 1,
        additionalInfoOrInstructions: "Make sure you also set kirby_flavor_preset to custom",
        buttonColor: "#FDCACE",
        buttonOutline: "#661E2A",
        buttonFontColor: "#111111",
        backgroundColorInCanvas: "#D6EAF2",
        backgroundColor: "#D6EAF2",
        palettes: [{
            name: "Default",
            colors: [
                "#B01810",
                "#F0E0E8",
                "#C8A0A8",
                "#A87070",
                "#E02018",
                "#F0A0B8",
                "#D07880",
                "#A85048",
                "#E8D0D0",
                "#E85048",
                "#D0C0C0",
                "#B08888",
                "#E87880",
                "#F8F8F8",
                "#B03830",
            ],
        }, {
            name: "Bubblegum",
            colors: [
                "#B50029",
                "#FF91C6",
                "#B0123B",
                "#630F0F",
                "#D60052",
                "#DE4873",
                "#D07880",
                "#000000",
                "#F770A5",
                "#E01784",
                "#CA4C74",
                "#A7443F",
                "#FF1784",
                "#FFA1DE",
                "#B03830",
            ],
        },
        {
            name: "Cherry",
            colors: [
                "#C70057",
                "#FF3554",
                "#AA0040",
                "#C02D47",
                "#E02068",
                "#C2183F",
                "#D03F80",
                "#872939",
                "#E82B47",
                "#E80067",
                "#D52F40",
                "#9F1C33",
                "#FD187F",
                "#F85068",
                "#D2386F",
            ],
        },
        {
            name: "Blueberry",
            colors: [
                "#5858e2",
                "#e6e6fa",
                "#bcbcf2",
                "#8484e6",
                "#2929ec",
                "#b5b5f0",
                "#847bd6",
                "#3232d6",
                "#d6d6ef",
                "#4a52ef",
                "#c6c6e6",
                "#4343ad",
                "#6767ff",
                "#f6f6fd",
                "#3139b6",
            ],
        },
        {
            name: "Lemon",
            colors: [
                "#B01810",
                "#F0E08D",
                "#C8A060",
                "#A87043",
                "#E03700",
                "#EFC063",
                "#D07818",
                "#A8501C",
                "#E8D070",
                "#E2501E",
                "#E8C55C",
                "#B08833",
                "#E8783B",
                "#F8F8A5",
                "#B03800",
            ],
        },
        {
            name: "Kiwi",
            colors: [
                "#9F4410",
                "#88F27B",
                "#57A044",
                "#227029",
                "#C75418",
                "#57BA23",
                "#1C6B00",
                "#2D6823",
                "#3FD744",
                "#E06C16",
                "#54C053",
                "#1A541E",
                "#F06B10",
                "#98F89A",
                "#B05830",
            ],
        },
        {
            name: "Grape",
            colors: [
                "#7C1060",
                "#CA8AE8",
                "#8250A5",
                "#604B7B",
                "#A52068",
                "#8D64B8",
                "#B73B80",
                "#672D9A",
                "#BA82D5",
                "#B55098",
                "#9F5CCF",
                "#632B74",
                "#CF78B5",
                "#DA98F8",
                "#8D3863",
            ],
        },
        {
            name: "Chocolate",
            colors: [
                "#6F1410",
                "#C2735C",
                "#5C351C",
                "#875440",
                "#9F2F0C",
                "#874C3B",
                "#88534C",
                "#4C1E00",
                "#B06458",
                "#921C16",
                "#9F5C54",
                "#5B3125",
                "#C01A14",
                "#CF785B",
                "#6B3125",
            ],
        },
        {
            name: "Marshmallow",
            colors: [
                "#a6a6a6",
                "#e6e6e6",
                "#bcbcbc",
                "#848484",
                "#909090",
                "#b5b5b5",
                "#848484",
                "#646464",
                "#d6d6d6",
                "#525252",
                "#c6c6c6",
                "#737373",
                "#949494",
                "#f6f6f6",
                "#545454",
            ],
        },
        {
            name: "Licorice",
            colors: [
                "#400000",
                "#6B6B6B",
                "#2B2B2B",
                "#181818",
                "#640000",
                "#3D3D3D",
                "#878787",
                "#020202",
                "#606060",
                "#980000",
                "#505050",
                "#474747",
                "#C80000",
                "#808080",
                "#AF0000",
            ],
        },
        {
            name: "Watermelon",
            colors: [
                "#2B4B10",
                "#EF8A9D",
                "#C84F6B",
                "#B74F54",
                "#126018",
                "#D85F6F",
                "#D06870",
                "#A24858",
                "#E77B8D",
                "#168025",
                "#DF5C68",
                "#9D4353",
                "#48953F",
                "#F897AD",
                "#B03830",
            ],
        },
        {
            name: "Orange",
            colors: [
                "#7B290C",
                "#FF9A00",
                "#B05C1C",
                "#8F3F0E",
                "#D23B0C",
                "#E08200",
                "#D05800",
                "#8A2B16",
                "#EF970A",
                "#E24800",
                "#E58F00",
                "#A03700",
                "#ED3B00",
                "#FFAF27",
                "#A84700",
            ],
        },
        {
            name: "Lime",
            colors: [
                "#AFA810",
                "#4FF29D",
                "#2BA04C",
                "#007043",
                "#C7C218",
                "#33BA5F",
                "#006B40",
                "#2D6823",
                "#1CD773",
                "#E0CF16",
                "#2DC06C",
                "#00543F",
                "#F0F010",
                "#43F8B2",
                "#B0A230",
            ],
        },
        {
            name: "Lavender",
            colors: [
                "#7C73B0",
                "#CACAE7",
                "#7B7BA8",
                "#5F5FA7",
                "#B57EDC",
                "#8585C5",
                "#5B5B82",
                "#474796",
                "#B2B2D8",
                "#B790EF",
                "#9898C2",
                "#6B6BB7",
                "#CDADFA",
                "#E6E6FA",
                "#976FBD",
            ],
        },
        {
            name: "Miku",
            colors: [
                "#373B3E",
                "#98d5d3",
                "#1aa5ab",
                "#168f95",
                "#4f5559",
                "#1dbac2",
                "#137a7f",
                "#093a3c",
                "#86cecb",
                "#a0afbc",
                "#62bfbb",
                "#50b8b4",
                "#bec8d1",
                "#bce4e2",
                "#91a2b1",
            ],
        }],
        currentDefaultPaletteIndex: 0,
        colorGroupData: [
            {
                colorGroupName: "Body",
                colorIndices: [13, 10, 8, 5, 1],
                indexOfMainColor: 13
            },
            {
                colorGroupName: "Feet/Outline",
                colorIndices: [14, 12, 11, 9, 7, 6, 4, 3, 2, 0],
                indexOfMainColor: 0
            }
        ],
        animations: [
            {
                animationName: "Walk",
                animationImages: [kirby_walk_03, kirby_walk_04, kirby_walk_05, kirby_walk_04, kirby_walk_03, kirby_walk_02, kirby_walk_01, kirby_walk_02],
                animationSeconds: 1
            },
            {
                animationName: "Fly",
                animationImages: [kirbyFly0, kirbyFly1, kirbyFly2, kirbyFly3, kirbyFly4],
                animationSeconds: .6
            },
            {
                animationName: "Swim",
                animationImages: [kirbySwim0, kirbySwim1, kirbySwim2, kirbySwim3, kirbySwim4, kirbySwim5, kirbySwim6, kirbySwim7],
                animationSeconds: .9
            },
            {
                animationName: "Run",
                animationImages: [kirbyRun0, kirbyRun1, kirbyRun2, kirbyRun3, kirbyRun4, kirbyRun3, kirbyRun2, kirbyRun1],
                animationSeconds: 1
            }
        ],
        currentAnimationIndex: 0
    },
    {
        characterName: "Gooey",
        yamlOptionName: 'gooey_flavor',
        firstColorIndexInYamlOption: 1,
        additionalInfoOrInstructions: "Make sure you also set gooey_flavor_preset to custom",
        buttonColor: "#13248E",
        buttonOutline: "#132438",
        buttonFontColor: "#EEEEEE",
        backgroundColorInCanvas: "#D6EAF2",
        backgroundColor: "#D6EAF2",
        palettes: [
            {
                name: "Default",
                colors: [
                    "#000909", //pupil, outer-most ring
                    "#0E1E2A", //ring-highlight
                    "#132438", //beard
                    "#132865", //face
                    "#13248E", //forehead
                    "#9E030F", //mouth
                    "#DF3838", //tongue
                    "#C5B2B3", //eye-lid
                    "#F6F6F6", //eye

                ]
            },

            {
                name: "Bubblegum",
                colors: [
                    "#CD539D",
                    "#D270AD",
                    "#F27CBF",
                    "#FF91C6",
                    "#FFA1DE",
                    "#B51810",
                    "#EF524A",
                    "#D6C6C6",
                    "#FFFFFF",
                ],
            },
            {
                name: "Cherry",
                colors: [
                    "#161600",
                    "#592910",
                    "#5A3118",
                    "#AB3918",
                    "#EB3918",
                    "#B51810",
                    "#EF524A",
                    "#D6C6C6",
                    "#FFFFFF",
                ],
            },
            {
                name: "Blueberry",
                colors: [
                    "#001616",
                    "#102959",
                    "#18315A",
                    "#1839AB",
                    "#1839EB",
                    "#B51810",
                    "#EF524A",
                    "#D6C6C6",
                    "#FFFFFF",
                ],
            },
            {
                name: "Lemon",
                colors: [
                    "#C8A031",
                    "#C5BD38",
                    "#D2CD48",
                    "#E2E040",
                    "#EAE2A0",
                    "#B51810",
                    "#EF524A",
                    "#D6C6C6",
                    "#FFFFFF",
                ],
            },
            {
                name: "Kiwi",
                colors: [
                    "#54A208",
                    "#5CB021",
                    "#6CB206",
                    "#8AC54C",
                    "#8DD554",
                    "#B51810",
                    "#EF524A",
                    "#D6C6C6",
                    "#FFFFFF",
                ],
            },
            {
                name: "Grape",
                colors: [
                    "#3D083D",
                    "#4B024B",
                    "#4C104C",
                    "#5F0A5F",
                    "#9F1D9F",
                    "#B51810",
                    "#EF524A",
                    "#D6C6C6",
                    "#FFFFFF",
                ],
            },
            {
                name: "Chocolate",
                colors: [
                    "#270C08",
                    "#481C10",
                    "#581E10",
                    "#5B2712",
                    "#743316",
                    "#B51810",
                    "#EF524A",
                    "#D6C6C6",
                    "#FFFFFF",
                ],
            },
            {
                name: "Marshmallow",
                colors: [
                    "#7F7F7F",
                    "#909090",
                    "#9D9D9D",
                    "#BFBFBF",
                    "#D2D2D2",
                    "#B51810",
                    "#EF524A",
                    "#D6C6C6",
                    "#FFFFFF",
                ],
            },
            {
                name: "Licorice",
                colors: [
                    "#141414",
                    "#2D2D2D",
                    "#404040",
                    "#585858",
                    "#7F7F7F",
                    "#B51810",
                    "#EF524A",
                    "#D6C6C6",
                    "#FFFFFF",
                ],
            },
            {
                name: "Watermelon",
                colors: [
                    "#954353",
                    "#AF4F68",
                    "#CD6073",
                    "#E06774",
                    "#E587A2",
                    "#17AF10",
                    "#4FE748",
                    "#D6C6C6",
                    "#FFFFFF",
                ],
            },
            {
                name: "Orange",
                colors: [
                    "#CF4700",
                    "#D85C08",
                    "#E26C04",
                    "#EA7B16",
                    "#EF8506",
                    "#B51810",
                    "#EF524A",
                    "#D6C6C6",
                    "#FFFFFF",
                ],
            },
            {
                name: "Lime",
                colors: [
                    "#1C4708",
                    "#105B1C",
                    "#186827",
                    "#187C3B",
                    "#188831",
                    "#B51810",
                    "#EF524A",
                    "#D6C6C6",
                    "#FFFFFF",
                ],
            },
            {
                name: "Lavender",
                colors: [
                    "#501E70",
                    "#673B87",
                    "#7848A7",
                    "#9067C7",
                    "#B57EDC",
                    "#B51810",
                    "#EF524A",
                    "#D6C6C6",
                    "#FFFFFF",
                ],
            },
        ],
        currentDefaultPaletteIndex: 0,
        colorGroupData: [
            {
                colorGroupName: "Body",
                colorIndices: [0, 1, 2, 3, 4],
                indexOfMainColor: 4
            },
            {
                colorGroupName: "Mouth",
                colorIndices: [5, 6],
                indexOfMainColor: 5
            },
            {
                colorGroupName: "Eyes",
                colorIndices: [7, 8],
                indexOfMainColor: 8
            }
        ],
        animations: [
            {
                animationName: "Grab",
                animationImages:
                    [gooey0,
                        gooey1,
                        gooey2,
                        gooey3,
                        gooey4,
                        gooey5,
                        gooey6,
                        gooey7,
                        gooey8,
                        gooey9,
                        gooey10,
                        gooey11,
                        gooey0, gooey1, gooey2, gooey3, gooey4, gooey2, gooey1],
                animationSeconds: 2
            }
        ],
        currentAnimationIndex: 0
    }
];